version: '3'

services:
  app:
    image: clear-solutions:1.0
    container_name: clear-solutions-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy


  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: task
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]