spring:
  application:
    name: Clear-Solutions-task

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  liquibase:
    change-log: db/changelog.sql

  jackson:
    property-naming-strategy: SNAKE_CASE